using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace UnrealSharpGAS.CodeGen;

[Generator]
public class AbilityTaskGenerator : IIncrementalGenerator
{
	private const string TargetAttribute = "UnrealSharp.UnrealSharpGAS.AbilityTaskAttribute";

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		var methods = context.SyntaxProvider
			.ForAttributeWithMetadataName(
				TargetAttribute,
				static (node, _) => node is MethodDeclarationSyntax m && m.Modifiers.Any(SyntaxKind.PartialKeyword),
				static (ctx, _) =>
				{
					var method = (IMethodSymbol)ctx.TargetSymbol;
					if (!method.IsStatic)
						return null;

					var attr = method.GetAttributes()
						.First(a => a.AttributeClass!.ToDisplayString() == TargetAttribute);

					var category = attr.ConstructorArguments.Length > 0
						? (string)attr.ConstructorArguments[0].Value!
						: "Ability|Tasks";

					var containingType = method.ContainingType;
					return new AbilityTaskMethodInfo(
						method.Name,
						method.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
						method.Parameters.Select(p =>
						{
							var typeName = p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
							var defaultValue = GetDefaultValueString(p);
							return (typeName, p.Name, defaultValue);
						}).ToList(),
						category,
						containingType.Name,
						containingType.ContainingNamespace.ToDisplayString());
				})
			.Where(static m => m != null)!;

		context.RegisterSourceOutput(methods, (spc, methodInfo) =>
		{
			var sb = new StringBuilder();
			sb.AppendLine("// <auto-generated/>");
			sb.AppendLine("#nullable enable");
			sb.AppendLine();
			sb.AppendLine("using UnrealSharp;");
			sb.AppendLine("using UnrealSharp.Attributes;");
			sb.AppendLine("using UnrealSharp.Core.Attributes;");
			sb.AppendLine();
			sb.AppendLine($"namespace {methodInfo.Namespace};");
			sb.AppendLine();
			sb.AppendLine($"public partial class {methodInfo.TypeName}");
			sb.AppendLine("{");

			sb.AppendLine("	[UMetaData(\"DefaultToSelf\", \"OwningAbility\")]");
			sb.AppendLine("	[UMetaData(\"HidePin\", \"OwningAbility\")]");
			sb.AppendLine("	[UMetaData(\"BlueprintInternalUseOnly\", \"true\")]");
			sb.AppendLine($"	[Category(\"{methodInfo.Category}\")]");
			sb.AppendLine("	[UFunction(FunctionFlags.BlueprintCallable)]");

			var parameters = string.Join(", ",
				methodInfo.Parameters.Select(p => string.IsNullOrEmpty(p.DefaultValue)
					? $"{p.TypeName} {p.Name}"
					: $"{p.TypeName} {p.Name} = {p.DefaultValue}"));

			sb.AppendLine($"	public static partial {methodInfo.ReturnTypeName} {methodInfo.MethodName}({parameters});");
			sb.AppendLine("}");

			spc.AddSource(
				$"{methodInfo.TypeName}.{methodInfo.MethodName}.abilitytask.g.cs",
				SourceText.From(sb.ToString(), Encoding.UTF8));
		});
	}

	private static string? GetDefaultValueString(IParameterSymbol parameter)
	{
		if (!parameter.HasExplicitDefaultValue)
			return null;

		var value = parameter.ExplicitDefaultValue;
		if (value is null)
			return "null";

		if (value is bool b)
			return b ? "true" : "false";

		if (value is string s)
			return $"\"{s}\"";

		if (value is char c)
			return $"'{c}'";

		if (parameter.Type.TypeKind == TypeKind.Enum)
			return $"({parameter.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}){value}";

		return value.ToString();
	}

	private sealed class AbilityTaskMethodInfo
	{
		public string MethodName { get; }
		public string ReturnTypeName { get; }
		public List<(string TypeName, string Name, string? DefaultValue)> Parameters { get; }
		public string Category { get; }
		public string TypeName { get; }
		public string Namespace { get; }

		public AbilityTaskMethodInfo(
			string methodName,
			string returnTypeName,
			List<(string TypeName, string Name, string? DefaultValue)> parameters,
			string category,
			string typeName,
			string ns)
		{
			MethodName = methodName;
			ReturnTypeName = returnTypeName;
			Parameters = parameters;
			Category = category;
			TypeName = typeName;
			Namespace = ns;
		}
	}
}
