using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace UnrealSharpGAS.CodeGen;

[Generator]
public class AttributeAccessorGenerator : IIncrementalGenerator
{
    private const string TargetAttribute = "UnrealSharp.UnrealSharpGAS.GameplayAttributeAccessorsAttribute";
    private const string TargetPropertyType = "FCSGameplayAttributeData";
    private const string BaseClassName = "UCSAttributeSet";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var properties = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                TargetAttribute,
                static (node, _) => node is PropertyDeclarationSyntax,
                static (ctx, _) =>
                {
                    var prop = (IPropertySymbol)ctx.TargetSymbol;
                    if (prop.Type.Name != TargetPropertyType)
                        return null;

                    var attr = prop.GetAttributes()
                        .First(a => a.AttributeClass?.ToDisplayString() == TargetAttribute);
                    var args = attr.ConstructorArguments;

                    return new PropertyAccessorInfo(
                        prop.Name,
                        args.Length > 0 ? (bool)args[0].Value! : true,
                        args.Length > 1 ? (bool)args[1].Value! : true,
                        args.Length > 2 ? (bool)args[2].Value! : true,
                        args.Length > 3 ? (bool)args[3].Value! : true,
                        prop.ContainingType.Name,
                        prop.ContainingNamespace.ToDisplayString());
                })
            .Where(static p => p != null)!;

        var grouped = properties.Collect()
            .Select(static (props, _) =>
            {
                var dict = new Dictionary<(string, string), List<PropertyAccessorInfo>>();
                foreach (var p in props)
                {
                    var key = (p.TypeName, p.Namespace);
                    if (!dict.TryGetValue(key, out var list))
                    {
                        list = new List<PropertyAccessorInfo>();
                        dict[key] = list;
                    }
                    list.Add(p);
                }
                return dict;
            });

        context.RegisterSourceOutput(grouped, (spc, groups) =>
        {
            foreach (var kvp in groups)
            {
                var key = kvp.Key;
                var typeName = key.Item1;
                var ns = key.Item2;
                var sb = new StringBuilder();
                sb.AppendLine("// <auto-generated/>");
                sb.AppendLine("#nullable enable");
                sb.AppendLine();
                sb.AppendLine("using UnrealSharp;");
                sb.AppendLine("using UnrealSharp.Core;");
                sb.AppendLine("using UnrealSharp.GameplayAbilities;");
                sb.AppendLine("using UnrealSharp.UnrealSharpGAS;");
                sb.AppendLine();
                sb.AppendLine($"namespace {ns};");
                sb.AppendLine();
                sb.AppendLine($"public partial class {typeName}");
                sb.AppendLine("{");

                foreach (var prop in kvp.Value)
                {
                    if (prop.GetAttr)
                        GenerateGetAttr(sb, prop);
                    if (prop.Get)
                        GenerateGet(sb, prop);
                    if (prop.Set)
                        GenerateSet(sb, prop);
                    if (prop.Init)
                        GenerateInit(sb, prop);
                }

                sb.AppendLine("}");
                spc.AddSource(
                    $"{typeName}.attributeaccessors.generated.cs",
                    SourceText.From(sb.ToString(), Encoding.UTF8));
            }
        });
    }

    private static void GenerateGetAttr(StringBuilder sb, PropertyAccessorInfo prop)
    {
        sb.AppendLine($"    public static FGameplayAttribute Get{prop.Name}Attribute()");
        sb.AppendLine("    {");
        sb.AppendLine($"        return GetGameplayAttribute(new TSubclassOf<{BaseClassName}>(typeof({prop.TypeName})), new FName(\"{prop.Name}\"));");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void GenerateGet(StringBuilder sb, PropertyAccessorInfo prop)
    {
        sb.AppendLine($"    public float Get{prop.Name}()");
        sb.AppendLine("    {");
        sb.AppendLine($"        TryGetAttributeCurrentValue(new FName(\"{prop.Name}\"), out float __value);");
        sb.AppendLine("        return __value;");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void GenerateSet(StringBuilder sb, PropertyAccessorInfo prop)
    {
        sb.AppendLine($"    public void Set{prop.Name}(float NewValue)");
        sb.AppendLine("    {");
        sb.AppendLine($"        TrySetAttributeBaseValue(new FName(\"{prop.Name}\"), NewValue);");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void GenerateInit(StringBuilder sb, PropertyAccessorInfo prop)
    {
        sb.AppendLine($"    public void Init{prop.Name}(float NewValue)");
        sb.AppendLine("    {");
        sb.AppendLine($"        TrySetAttributeBaseValue(new FName(\"{prop.Name}\"), NewValue);");
        sb.AppendLine("    }");
    }
}

internal class PropertyAccessorInfo
{
    public string Name { get; }
    public bool GetAttr { get; }
    public bool Get { get; }
    public bool Set { get; }
    public bool Init { get; }
    public string TypeName { get; }
    public string Namespace { get; }

    public PropertyAccessorInfo(
        string name, bool getAttr, bool get, bool set, bool init,
        string typeName, string ns)
    {
        Name = name;
        GetAttr = getAttr;
        Get = get;
        Set = set;
        Init = init;
        TypeName = typeName;
        Namespace = ns;
    }
}
